apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: friendly-container
    image: "alpine:3.4"
    command: ["/bin/echo", "hello", "world"]
    securityContext:
      capabilities:
        add:
        - SYS_NICE
        drop:
        - KILL'

################
#
# Creates a pod containig one container that runs echo hello world.
# Furthermore the Capability SYS_NICE is added to the Container, which allows the 
# Processes inside the Container to change their and others nice values for CPU scheduling.
# The Kill Capability is removed from the processes in the Container.
# This restricts processes inside the Container to kill processes. 
#
#
# Source: https://unofficial-kubernetes.readthedocs.io/en/latest/concepts/policy/container-capabilities/
#
################